### ISSUE TITLE
How is this different from NJKScrollFullScreen?

### ISSUE THREAD

**Issue by eremzeit** [pixyzehn/MediumScrollFullScreen#1]
You reference it so it might be worth explaining why you decided to make another one.

**Comment by pixyzehn** [comment]
@eremzeit 
I am very sorry for being so late. I wanted to express the library that is similar to Medium's screen on web view and offer that for developer easily.

**Comment by eremzeit** [comment]
Ahh that makes sense.  Thanks for open sourcing it :)
